HACK: recipes: disable cmem due to breakage
src/cmem/module/cmemk.c:920:12: error: void value not ignored as it ought to be

Signed-off-by: Denys Dmytriyenko <denys@ti.com>