statcol: suppress "ldflags" QA error
Fixes:
ERROR: statcol-1.0-r0_3 do_package_qa: QA Issue: File /usr/bin/statcol in package statcol doesn't have GNU_HASH (didn't pass LDFLAGS?) [ldflags]

Need to change Makefile to pass proper LDFLAGS.

Signed-off-by: Denys Dmytriyenko <denys@konsulko.com>
Cc: Keerthy <j-keerthy@ti.com>