ti-llvm3.6: depend on valgrind
If valgrind is not yet staged, may cause this error:

| .../git/lib/Support/Valgrind.cpp:20:31: fatal error: valgrind/valgrind.h: No such file or directory
|  #include <valgrind/valgrind.h>
|                                ^
| compilation terminated.

Signed-off-by: Denys Dmytriyenko <denys@ti.com>