HACK: packagegroup-arago-test: disable omapdrmtest due to breakage
git/util/demux.c:87:23: error: 'CODEC_ID_H264' undeclared (first use in this function)

Signed-off-by: Denys Dmytriyenko <denys@ti.com>