Revert "optee: Update SRCREV for client, os and test"
Latest optee-client fails with gcc 6.2:

test_20000.c:399:17: error: 'real_offset' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     real_offset += rand() % (BLOCK_SIZE - 1);
                 ^~

This reverts commit 5e0a9a5ce11f5cb773bf44c327a623b5c39c8a72.