matrix, packagegroup: disable qtwebkit and matrix gui for omapl138/armv5
Latest qtwebkit 5.15 fails to build for armv5 with bunch of errors like:

Error: selected processor does not support `movw r8,#:lower16:.Lllint_op_enter-.LrelativePCBase' in ARM mode

Since omapl138/armv5 is already underpowered and has no graphics, it doesn't
make too much sense to run matrix gui in qtwebkit while software rendering
everything offscreen.

Signed-off-by: Denys Dmytriyenko <denys@konsulko.com>
Signed-off-by: Ryan Eatmon <reatmon@ti.com>