gstreamer1.0-plugins-hevc: suppress gcc10 multiple definitions of buffArray
Woraround for the following gcc10 build error:
.../src/gsth265buf.h:126: multiple definition of `buffArray';
.libs/libgsth265dec_la-gsth265dec.o:.../src/gsth265buf.h:126: first defined here

Needs to be resolved properly in the code later:
https://gcc.gnu.org/gcc-10/porting_to.html

Signed-off-by: Denys Dmytriyenko <denys@konsulko.com>