linux-libc-headers: handle removal of asm/kvm.h in kernel 5.8+
Multilib handling is done in linux-libc-headers.inc in oe-core and the version
in dunfell handles the list for 5.4, while the list for 5.10 has no asm/kvm.h
due to kernel commit: 541ad0150ca4 [arm: Remove 32bit KVM host support].

Fixes this error on ARM32 platforms when using internal toolchain:
ERROR: linux-libc-headers-5.10-r0.arago0 do_install: oe_multilib_header: Unable to find header asm/kvm.h.

Also, dependency on rsync-native is now upstream.

Signed-off-by: Denys Dmytriyenko <denys@konsulko.com>
Signed-off-by: Yogesh Siraswar <yogeshs@ti.com>