ti-test: fix string expansion
bb conditional util expansion was done in '' causing the below error

```
bb.data_smart.ExpansionError: Failure expanding variable ARAGO_TI_TEST, expression was ... ${@bb.utils.contains('MACHINE_FEATURES', 'mmip', 'omapdrmtest', '', d)} cmem-test     ', d)}
which triggered exception SyntaxError: invalid syntax (Var <ARAGO_TI_TEST>, line 1)
```

fixed the expansion to within "".

Signed-off-by: Gowtham Tammana <g-tammana@ti.com>
Reviewed-by: Denys Dmytriyenko <denys@konsulko.com>