qtwebkit: Fix no X11 build
qtwebkit build is failing to set EGL_NO_X11 on platforms with no x11
support causing below failure.

```{.package=qtwebkit .version=dunfell}
In file included from
tisdk/build/arago-tmp-external-arm-glibc/work/aarch64-linux/qtwebkit/5.14.2+gitAUTOINC+ab1bd15209-r0.arago7/recipe-sysroot/usr/include/EGL/egl.h:39,
                from tisdk/build/arago-tmp-external-arm-glibc/work/aarch64-linux/qtwebkit/5.14.2+gitAUTOINC+ab1bd15209-r0.arago7/git/Source/WebCore/platform/graphics/opengl/Extensions3DOpenGLES.cpp:36:
tisdk/build/arago-tmp-external-arm-glibc/work/aarch64-linux/qtwebkit/5.14.2+gitAUTOINC+ab1bd15209-r0.arago7/recipe-sysroot/usr/include/EGL/eglplatform.h:134:10: fatal error: X11/Xlib.h: No such file or directory
  134 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```

Setting up the flag EGL_NO_X11 when X11 target is disabled.

Signed-off-by: Gowtham Tammana <g-tammana@ti.com>
Reviewed-by: Denys Dmytriyenko <denys@konsulko.com>