ti-test: fix build errors with nested conditional operation
nested conditional operation like this
${@oe.utils.conditional(<condition>, ${@bb.utils.contains()}

is causing build issues on some of the older build machines like this.

Missing or unbuildable dependency chain was: ['tisdk-default-image', 'ti-test', "'',"]
ERROR: Nothing RPROVIDES ''omapdrmtest',' (but <>/ti-test.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target ''omapdrmtest',' is unbuildable, removing...
Missing or unbuildable dependency chain was: ["'omapdrmtest',"]
ERROR: Nothing RPROVIDES ''mmip',' (but <>/ti-test.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target ''mmip',' is unbuildable, removing...
Missing or unbuildable dependency chain was: ["'mmip',"]

This patch fixes such build issue.

Suggested-by: Denys Dmytriyenko <denis@denix.org>
Signed-off-by: Praneeth Bajjuri <praneeth@ti.com>
Reviewed-by: Gowtham Tammana <g-tammana@ti.com>