battleship: Fix "error: 'sleep' was not declared in this scope
* Newer toolchains are alot stricter and missing header files are now being
  flagged as errors.
* Update battleship commit to pull in the patch that fixes this problem.

Signed-off-by: Franklin S. Cooper Jr <fcooper@ti.com>
Signed-off-by: Denys Dmytriyenko <denys@ti.com>